runtime: python37

entrypoint: gunicorn -b :$PORT main:app --timeout 600
beta_settings:
  cloud_sql_instances: abcd-356108:asia-south1:database=tcp:5432
runtime_config:
 python_version: 3



# handlers:
#   - url: .*
#     script: main.app
